[package]
name = "primer_clase"
version = "0.1.0"
authors = ["mlafroce <mlafroce@gmail.com>", "juanbono94@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
